### ISSUE TITLE
Wrong package names in resources directory

### ISSUE THREAD

**Issue by dlemmermann** [mkpaz/atlantafx#10]
The directories in the resources folder start with "assets", but the module-info.java exports them like this:    

```
 // resources
    opens atlantafx.sampler.assets.fonts;
    opens atlantafx.sampler.assets.highlightjs;
    opens atlantafx.sampler.assets.styles;
```

**Comment by dlemmermann** [comment]
I see the "resources" element in the pom.xml file but IntelliJ seems to have an issue with this, or maybe even Maven. Currently I can't get the project to work.

**Comment by mkpaz** [comment]
Unlikely Maven, otherwise GitHub Actions and Conveyor won't work. I also use IntelliJ, which gives me exactly the same warning, but I have no problems building the project. From my experience, "Build Project" (^F9) function is somewhat buggy, probably because it uses incremental compilation. Plain Maven Running Configuration should not produce any errors.

**Comment by mkpaz** [comment]
Sorry, I can't reproduce this, but I admit that such configuration isn't very obvious, so it will be removed in the future versions as a part of refactoring.
