### ISSUE TITLE
Table row height is jumping

### ISSUE THREAD

**Issue by PavelTurk** [mkpaz/atlantafx#107]
This is my code:

```
public class JavaFxTest10 extends Application {

    private static record Foo (String a, int b, int c, int d, int e, int f, int g, int h) {};

    private TableView<Foo> table = new TableView<>(FXCollections.observableList(
            List.of(new Foo("A", 1, 2, 3, 4, 5, 6, 7),
                    new Foo("AA", 10, 20, 30, 40, 50, 60, 70),
                    new Foo("AAA", 100, 200, 300, 400, 500, 600, 700))));

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        Application.setUserAgentStylesheet(new Dracula().getUserAgentStylesheet());
        var aColumn = new TableColumn<Foo, String>("A");
        aColumn.setCellValueFactory((data) ->  new ReadOnlyObjectWrapper<>(data.getValue().a()));
        aColumn.setResizable(true);

        var bColumn = new TableColumn<Foo, Integer>("B");
        bColumn.setCellValueFactory((data) ->  new ReadOnlyObjectWrapper<>(data.getValue().b()));
        bColumn.setResizable(true);

        var cColumn = new TableColumn<Foo, Integer>("C");
        cColumn.setCellValueFactory((data) ->  new ReadOnlyObjectWrapper<>(data.getValue().c()));
        cColumn.setResizable(true);

        var dColumn = new TableColumn<Foo, Integer>("D");
        dColumn.setCellValueFactory((data) ->  new ReadOnlyObjectWrapper<>(data.getValue().d()));
        dColumn.setResizable(true);

        var eColumn = new TableColumn<Foo, Integer>("E");
        eColumn.setCellValueFactory((data) ->  new ReadOnlyObjectWrapper<>(data.getValue().e()));
        eColumn.setResizable(true);

        var fColumn = new TableColumn<Foo, Integer>("F");
        fColumn.setCellValueFactory((data) ->  new ReadOnlyObjectWrapper<>(data.getValue().f()));
        fColumn.setResizable(true);

        var gColumn = new TableColumn<Foo, Integer>("G");
        gColumn.setCellValueFactory((data) ->  new ReadOnlyObjectWrapper<>(data.getValue().g()));
        gColumn.setResizable(true);

        var hColumn = new TableColumn<Foo, Integer>("H");
        hColumn.setCellValueFactory((data) ->  new ReadOnlyObjectWrapper<>(data.getValue().h()));
        hColumn.setResizable(true);

        table.getColumns().addAll(aColumn, bColumn, cColumn, dColumn, eColumn, fColumn, gColumn, hColumn);
        table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN);

        table.getStyleClass().add(Styles.DENSE);
        VBox.setVgrow(table, Priority.ALWAYS);

        VBox root = new VBox(new TextField(), table);
        var scene = new Scene(root, 400, 300);
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
```
This is demo:
![Peek 2024-08-11 20-36](https://github.com/user-attachments/assets/2b5a0679-939b-4300-952f-0a220b8b0dbc)

I've noticed that it depends on two factors - the count of columns and stage initial width (400).

**Comment by mkpaz** [comment]
That's another JavaFX issue. The AtlantaFX `.table-view` uses a fixed cell height by default. So there are no paddings to shrink as happened in your case. 

Judging by the window decorations, you're running Ubuntu Gnome. Are you by any chance using the Wayland session? Because I cannot reproduce this in KDE X11 (theme doesn't matter).

![table](https://github.com/user-attachments/assets/bece3a8c-e6db-4bb8-8384-923eb7f305cf)

**Comment by mkpaz** [comment]
Sorry, I can't reproduce this. Neither with Modena, nor with AtlantaFX themes. This is probably something specific to your OS, JavaFX or JDK version. That's why I asked about Wayland. You can try to reset [-fx-cell-size](https://github.com/mkpaz/atlantafx/blob/3ffaf3d24345c28d5abb3c9122698a1ee9727a9c/styles/src/components/_data.scss#L408) (set it to `-1`) on the specific table via CSS or to set in pixels, not in `em`. Maybe this will help. There are no paddings applied and judging from the GIF, font size isn't changing, so it's triggered somewhere inside TableView resize logic.

![image](https://github.com/user-attachments/assets/f09b74b1-eddb-40aa-b873-700caf769457)

**Comment by mkpaz** [comment]
Thanks! I think the problem is probably in `-fx-cell-size` property, so I've filed a bug too, but it's still not accepted.

**Comment by andy-goryachev-oracle** [comment]
while we figuring out the issue, you may want to try setting `-fx-fixed-cell-size` on the `.table-view`

**Comment by andy-goryachev-oracle** [comment]
@PavelTurk : it's hard to diagnose a possible problem without the reproducer, but if you create a small self-contained code example I'll help you create a JBS ticket.
