### ISSUE TITLE
Components in Scene Builder 

### ISSUE THREAD

**Issue by brandonrock919** [mkpaz/atlantafx#18]
Does the library will be fully in scene builder as I saw, there are only 5-6 components right now 
By the way amazing job

**Comment by mkpaz** [comment]
AtlantaFX is not a controls library, it's CSS theme library or [user agent stylesheet](https://openjfx.io/javadoc/17/javafx.graphics/javafx/application/Application.html#setUserAgentStylesheet(java.lang.String)) that works with existing JavaFX controls. It does provide several popular controls in [the separate module](https://github.com/mkpaz/atlantafx/tree/master/base), but those are absolutely optional. You can use bare CSS file just like `Application.setUserAgenStylesheet("/path/to/css/file")`.

Regarding Scene Builder, I don't know whether it can be supported or not. Currently Scene Builder only supports default JavaFX themes (Modena and Caspian) and Gluon themes for mobile. That's hard-coded support. Since, there's [no such notion as theme](https://github.com/openjdk/jfx/pull/511) in JavaFX (yet) I suppose the answer to the question is no. Someone should contribute this feature to JavaFX first and then implement it for Scene Builder.

I stopped using Scene Builder long ago as a) it was nearly abandoned for years; b) I prefer MVVM to MVC; c) `FXMLLoader` never shined in terms of performance.
