### ISSUE TITLE
Adding more size options?

### ISSUE THREAD

**Issue by RealThanhpv** [mkpaz/atlantafx#29]
Currently, it has small, normal, and large. What is the best way to have more options?

**Comment by mkpaz** [comment]
You mean adding `xs` and `xl`? Unlikely, I think such decision would add high maintenance cost and has from little to no practical value, because AtlantaFX for now is targets desktop only and here is an example from MD spec:

![image](https://user-images.githubusercontent.com/25181998/206888304-041e3f6e-21d2-4419-9d56-449db22c6e03.png)

As much as I remember many Web component frameworks also support 3 sizes only. E.g. [iView](https://www.iviewui.com/view-ui-plus/component/base/button#size) or [Prime](https://www.primefaces.org/primevue/button).

Overall, I think improving current sizes to fit interface font more smoothly and maybe adding compact theme flavor in the future is better time investment, but adding examples to the docs to guide user how to change component size via custom CSS might be a good idea.

**Comment by RealThanhpv** [comment]
An extra to the question I have made? Can we switch between sizes (small, normal, large) in one shot (such as switching pseudo class for .root) . 
I am not so sure. Is it a good idea to add size choices here 
<img width="1012" alt="Screen Shot 2022-12-12 at 09 57 22" src="https://user-images.githubusercontent.com/94328752/206951336-d653bd89-c805-4258-9f07-2cca9ec5b2da.png">

**Comment by RealThanhpv** [comment]
An extra to the question. I am not so sure but is it a good idea to make it possible and easy to switch sizes in one shot (like   themization, switching .root pseudo-class). I do not see it in docs?

**Comment by mkpaz** [comment]
Sadly, JavaFX only partially implements CSS 2.1 spec and [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) is a CSS 4 module. You can define custom variables at any level, but variable type is restricted. It can be only color type variable. See [CSS ref](https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html) or docs for looked-up colors. There's no way to manipulate controls size at runtime via variables except changing the font size at `.root` level.
