### ISSUE TITLE
AtlantaFX themes prevent Ikonli's FontIcon from being configurable

### ISSUE THREAD

**Issue by Col-E** [mkpaz/atlantafx#31]
## Summary

When using an AtlantaFX theme (NordDark in my case), usage of Ikonli's `FontIcon` size/color setters are ignored. 

## Preview

```java
FontIcon graphic = FontIcon.of(icon, 16, Color.RED /* or any color */); // will be 18px and white
// graphic.setStyle("-fx-icon-color: red;"); // overrides the color to red, but breaks the icon, making it a red square
```

With NordDark applied: 

![image](https://user-images.githubusercontent.com/21371686/211235095-b68a6d9b-a834-4794-9d7f-687619a4268e.png)

Without: 

![image](https://user-images.githubusercontent.com/21371686/211235127-03891477-f687-48ec-b619-2109a673c127.png)

## Diagnosis

Inside NordDark is the following snippet:
```css
.ikonli-font-icon {
  -fx-icon-color: -color-fg-default;
  -fx-fill: -color-fg-default;
  -fx-icon-size: 18px;
}
```
It'd be nice if these were defaults, not forced values. I'm not sure why defining these properties prevents configuration in `FontIcon`. Typically when a control is styled in CSS and you use an explicit `setColor(...)` the call to the setter will override what is in the CSS. Perhaps this an issue on Ikonli's side?

**Comment by mkpaz** [comment]
Icon size should really be specified as `em` to scale with the font size, but unfortunately, [Ikonli does not support that](https://github.com/kordamp/ikonli/issues/150). I can't add icon size support for small / large button for the same reason. If you check the issue, this is how Ikonli handles CSS. It just overrides Node `style` value, so your programmatic config overrides all of the CSS properties at once. This is not how styled properties supposed to work, but it probably implemented that way because relevant JavaFX API is private, I'm not sure.

**Comment by Col-E** [comment]
> so your programmatic config overrides all of the CSS properties at once

💀 welp...

Guess I'll just re-implement a custom node for this then.
