### ISSUE TITLE
Is there a quick start guide on how to use this in a my project with FXML and or standard java

### ISSUE THREAD

**Issue by Malumbo21** [mkpaz/atlantafx#32]

**Comment by mkpaz** [comment]
Yes, see getting [started section](https://github.com/mkpaz/atlantafx#getting-started). All you need is to set a theme. If you need Scene Builder integration, it's tricky because Scene Builder doesn't support third-party themes, but you can workaround it. See the [pinned issue](https://github.com/mkpaz/atlantafx/issues/27).
