### ISSUE TITLE
Add dense TreeView

### ISSUE THREAD

**Issue by Naton1** [mkpaz/atlantafx#6]
This would be great to have. I'm looking at adding this to a project I have, and right now, the TreeView is a bit too large for usability purposes. Adding a dense style class to TreeView like ListView would be awesome.

Also, awesome project!

**Comment by mkpaz** [comment]
Good idea and it's easy enough to implement. In fact you can already do this by manipulating vertical [tree-cell paddings](https://github.com/mkpaz/atlantafx/blob/master/styles/src/components/_data.scss#L372).

normal list cell size = 2.8em / 0.9 em paddings 
dense list cell size = 2em / 0.5 em paddings
tree cell size = 2em / 0.5 em paddings

So, tree view is kind of already "dense" comparing to list/table view. But since increasing tree view padding makes it rather ugly, it thinks adding dense style with 0.25 - 0.3 em paddings makes sense.

![Unsaved Image 2](https://user-images.githubusercontent.com/25181998/186626024-7eb8b468-d8e4-4a79-9e22-126423346b4e.png)

**Comment by mkpaz** [comment]
Fixed with https://github.com/mkpaz/atlantafx/commit/197618ef2ec95c8532b4f0d07e3a5999d71b9d55

**Comment by Naton1** [comment]
Thanks!
