### ISSUE TITLE
Some incompatibility with ControlsFX

### ISSUE THREAD

**Issue by mipastgt** [mkpaz/atlantafx#8]
I just attempted to give AtlantaFX a try in one of my applications but I got a lot of errors (see attachment) which all originated in ControlsFX. I don't know how to react to that. Does it mean that ControlsFX cannot be used with AtlantaFX or is there anything that can be done to avoid them?

[errors.txt](https://github.com/mkpaz/atlantafx/files/9445329/errors.txt)

**Comment by mkpaz** [comment]
ControlsFX relies on Modena/Caspian [color variables](https://gist.github.com/maxd/63691840fc372f22f470#file-modena-css-L95) ([looked-up colors](https://openjfx.io/javadoc/17/javafx.graphics/javafx/scene/doc-files/cssref.html#typecolor)), whereas AtlantaFX [follows](https://github.com/mkpaz/atlantafx/blob/master/styles/src/general/_root.scss#L8) [GitHub Primer color system](https://primer.style/primitives/colors/). The errors you see mean that those looked-up colors couldn't be resolved, which is expected behavior. I don't think projects itself are not compatible, but you can't use the default ControlsFX stylesheet, because again it expected to be used with bundled OpenJFX themes only. If you want to use them together you should style each ControlsFX component using AtlantaFX color variables.

**Comment by mipastgt** [comment]
After investigating the issue a little bit more I still think that it would be a good idea to provide the original JavaFX color definitions, adapted to the chosen theme, as a potential fall-back for all external controls which rely on them. This is of course not a perfect solution but they could at least be used as is without having to do a full re-styling for them.

**Comment by mkpaz** [comment]
I think that wouldn't work because common Modena (and its derivatives) stylesheet highly use gradients and derived colors. Even if you'd changed color variables, you can also do nothing with background insets without re-styling. I don't mind including an additional module to support some third-party libs and compile it to the separate stylesheet(s) which can be optionally added to the scene. That won't happen in short/mid-term perspective though.
