### ISSUE TITLE
Calendar does not initialize with date

### ISSUE THREAD

**Issue by rzillmann** [mkpaz/atlantafx#83]
Hello, after using AtlantaFX it came to my attention that the Calendar does initiate the ui and the model differently which is kind of unintuitive and a little annoying. I think the displayed value and the underlying value should match.

Used theme: cupertino dark

**Expected behaviour**

If a Calendar is instantiated (code or via fxml) i want to see the current date ( if not stated otherwise) is displayed visualized in the component after the ui is displayed.

If i call getValue i want to get the current date

**Actual behaviour**
The current date is displayed in the UI correctly
getValue returns null

**Ways to reproduce**
After instantiating a Calendar call getValue without setting the value before

**Comment by rzillmann** [comment]
Just stumbled across the same problem with DatePicker, setValue does not set the Value in the field anymore. Checked it against a plain javafx Datepicker and there it gets displayed correctly

**Comment by mkpaz** [comment]
Sorry, I don't follow. There is indeed a bug in the calendar constructor, but it's not related to this issue. 

If I instantiate a calendar with null value, `getValue()` returns null and the skin only highlights today's (`.today`) but not selected (`.selected`) value. 

![image](https://github.com/user-attachments/assets/a36d6de8-4c7b-44d4-8365-fd02d7427f23)

If I instantiate a calendar with non-null value, it displayed correctly and `getValue()` returns that value.

> Just stumbled across the same problem with DatePicker, setValue does not set the Value in the field anymore. Checked it against a plain javafx Datepicker and there it gets displayed correctly

It's the same control. I created (copy-pasted, actually) the Calendar only because JavaFX doesn't export `DatePickerContent` and inline date picker is kinda mandatory these days.

**Comment by rzillmann** [comment]
My bad you are absolutly right. I got bamboozled pretty good by the two blue tones and the fact is was working with today.
Was totally not think of "thats a generic today marker" so my wording was bad. I would like to change this to a question:

What's the reason for not setting today as default instead of null? I can't even "unselect" if i clicked a date once

**Comment by mkpaz** [comment]
For example, when it comes to validation, it's important to know whether the user has selected something or not in order to provide more informative error messages. "You need to select a date" versus "Your date is greater than X". So, I think null value is really important here.

As for unselecting, that like pretty much everyone datepicker works [1](https://antdv.com/components/calendar/#components-calendar-demo-card), [2](https://blueprintjs.com/docs/#datetime/datepicker), [3](https://mui.com/x/react-date-pickers/date-picker/#available-components). The Calendar supports two optional slots: top and bottom. You can put a unselect button here if you need to.

TickTick:

![image](https://github.com/user-attachments/assets/de199f60-cc6b-41fb-904f-77c33e53ea98)

Trello:

![image](https://github.com/user-attachments/assets/72b4d111-7133-49cb-aa9f-2376dbd771c0)

**Comment by rzillmann** [comment]
True, thank you for the clarification
